### PR TITLE
feat/footer

### PR DESCRIPTION
**Pull request by itnoj15**
- Update footer to be responsive

스크린샷 2024-06-20 오후 11 22 35

### CODE REVIEW

**Comment by alextio** [comment]
Please de-commit the `package-lock.json` and `yarn.lock` files

**Review by alextio — APPROVED** [review]

**Comment by CheddarChoi** [comment]
Seems like my comments were not reflected.

**Comment by alextio** [comment]
Sorry. What comments?

**Comment by CheddarChoi** [comment]
Sorry, I think I didn't submit the review. Just submit it

**Comment by alextio** [comment]
@itnoj15 can you create a new PR with DaEun's suggestions

**Comment by itnoj15** [comment]
Okay, I will create a new PR.

**Pull request merged**
